name: Python CI # Workflow name

# Events: push, pull -> Trigger workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest # Containers: Windows, Ubuntu, macOS

    steps:
      # Step 1: Check out the code from repository
      - name: Check Out Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

       # Step 5: Run tests

      - name: Test with pytest
        run: pytest
